### ISSUE TITLE
2022.3.1报错

### ISSUE THREAD

**Issue by xsunflowers** [huangbaihua001/RestfulToolkitX#87]
java.lang.Throwable: Activities registered via registerPostStartupActivity must be dumb-aware: com.intellij.util.DisposeAwareRunnable@7e392b52
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.ide.startup.impl.StartupManagerImpl.registerPostStartupActivity(StartupManagerImpl.kt:132)
	at jiux.net.plugin.utils.ToolkitUtil.runWhenInitialized(ToolkitUtil.java:35)
	at jiux.net.plugin.restful.navigator.RestServicesNavigator.initComponent(RestServicesNavigator.java:102)
	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:45)
	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:154)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance$lambda$1(BaseComponentAdapter.kt:133)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:132)
	at com.intellij.serviceContainer.BaseComponentAdapter.access$createInstance(BaseComponentAdapter.kt:19)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invokeSuspend(BaseComponentAdapter.kt:181)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceAsync(BaseComponentAdapter.kt:176)
	at com.intellij.serviceContainer.ComponentManagerImpl.createComponentsNonBlocking(ComponentManagerImpl.kt:428)
	at com.intellij.serviceContainer.ComponentManagerImpl$createComponentsNonBlocking$1.invokeSuspend(ComponentManagerImpl.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by anicething** [comment]
I  meet this problem too.

**Comment by JYShaw** [comment]
me too 🙋‍♂️

**Comment by hnyyghk** [comment]
之前#75 已经尝试修复过这个问题了，但在#73 中提到的如下解决方案有缺陷，回滚了代码
我在IntelliJ IDEA 2021.3.3 (Ultimate Edition)使用2.0.9版本复现了#79 窗口异常这个问题


> 注释掉runWhenInitialized方法中的这四行，统一走下面的invokeLater方法

```
        if (!project.isInitialized()) {
            StartupManager.getInstance(project).runAfterOpened(DisposeAwareRunnable.create(r, project));
            return;
        }
```


对比了com.jetbrains:ideaIU:2022.2.4和2022.3的StartupManagerImpl中registerPostStartupActivity方法
发现该方法在2022.3去除了针对非DumbAware的Runnable支持，warn也改为了error
并且该方法已经被标记为过时，建议使用runAfterOpened，这个方法自2020.1 (201.6668.113 build)可用

![image](https://user-images.githubusercontent.com/17867953/205423947-f52e04fb-1330-4f1e-be95-46045ec588af.png)
（com.jetbrains:ideaIU:2022.2.4中registerPostStartupActivity方法实现）
![image](https://user-images.githubusercontent.com/17867953/205424058-42df9de4-4c9e-47e0-b0af-f3e69d172f91.png)
（com.jetbrains:ideaIU:2022.3中registerPostStartupActivity方法实现）
![image](https://user-images.githubusercontent.com/17867953/205424775-08ef8646-d8ae-41d6-a6f9-643f6f31da88.png)
（com.jetbrains:ideaIU:2022.3中registerPostStartupActivity方法已经被标记为过时，建议使用runAfterOpened）
![image](https://user-images.githubusercontent.com/17867953/211565254-b777ca60-f6ee-4061-a01f-fb18be69624e.png)
（com.jetbrains:ideaIU:2022.3中runAfterOpened方法实现）

先将registerPostStartupActivity方法替换为runAfterOpened
并模仿com.jetbrains:ideaIU:2022.2.4中registerPostStartupActivity方法实现，将Runnable进行包装DumbService.getInstance(project).unsafeRunWhenSmart(r)


我自己编译了个测试版本，在IntelliJ IDEA 2021.3.3 (Ultimate Edition)以及IntelliJ IDEA 2022.3.1 (Ultimate Edition)测试通过
欢迎大家测试
https://github.com/hnyyghk/RestfulToolkitX/releases/tag/v2.1.0-test
代码改动已经发起PR
